// GENERATED by tool/generate_tokens.dart. Do not edit.

import 'package:flutter/painting.dart';

abstract final class FujinColor {
  static const ekklo = Color(0xFF7A4BC9);
  static const ekkloClair = Color(0xFFECE5F7);
  static const ekkloFonce = Color(0xFF5B3A99);
  static const fujin = Color(0xFF2F5E34);
  static const hai = Color(0xFF6F6857);
  static const haiClair = Color(0xFF8A826C);
  static const kin = Color(0xFFD4A548);
  static const kinClair = Color(0xFFF3E6C4);
  static const kinFonce = Color(0xFF8C6418);
  static const kinari = Color(0xFFE3DAC0);
  static const kinu = Color(0xFFFFFCF4);
  static const matcha = Color(0xFFDCE8D5);
  static const mfp = Color(0xFF1E6BD6);
  static const mfpClair = Color(0xFFDCE6F7);
  static const mfpMoyen = Color(0xFFBBD0EB);
  static const shu = Color(0xFFB23A26);
  static const shuClair = Color(0xFFF4DDD6);
  static const sora = Color(0xFF3F6A82);
  static const soraClair = Color(0xFFDDE7EC);
  static const sumi = Color(0xFF1B1A17);
  static const usuzumi = Color(0xFFBDB49C);
  static const washi = Color(0xFFF7F1E0);
}

abstract final class FujinRole {
  static const Color bordureCarte = FujinColor.kinari;
  static const Color bordureFilet = FujinColor.kinari;
  static const Color bordureSeparateur = FujinColor.kin;
  static const Color boutonAlerteFond = FujinColor.shu;
  static const Color boutonAlerteTexte = FujinColor.kinu;
  static const Color boutonInactifFond = FujinColor.kinari;
  static const Color boutonInactifTexte = FujinColor.haiClair;
  static const Color boutonPrincipalFond = FujinColor.sumi;
  static const Color boutonPrincipalTexte = FujinColor.kinu;
  static const Color fondAlerte = FujinColor.shuClair;
  static const Color fondCarte = FujinColor.kinu;
  static const Color fondInfo = FujinColor.soraClair;
  static const Color fondPage = FujinColor.washi;
  static const Color fondSombre = FujinColor.sumi;
  static const Color fondSucces = FujinColor.matcha;
  static const Color fondVoile = FujinColor.sumi;
  static const Color objectifAtteint = FujinColor.fujin;
  static const Color objectifAtteintFond = FujinColor.matcha;
  static const Color objectifDepasse = FujinColor.shu;
  static const Color objectifDepasseFond = FujinColor.shuClair;
  static const Color objectifEnCours = FujinColor.mfp;
  static const Color objectifJourChoisi = FujinColor.sumi;
  static const Color objectifMinimumReste = FujinColor.mfpMoyen;
  static const Color objectifNonAtteint = FujinColor.mfp;
  static const Color objectifNonAtteintFond = FujinColor.mfpClair;
  static const Color objectifPiste = FujinColor.kinari;
  static const Color sourceEkklo = FujinColor.ekklo;
  static const Color sourceEkkloFond = FujinColor.ekkloClair;
  static const Color sourceEkkloTexte = FujinColor.ekkloFonce;
  static const Color sourceMfp = FujinColor.mfp;
  static const Color texteAlerte = FujinColor.shu;
  static const Color texteInactif = FujinColor.usuzumi;
  static const Color texteLien = FujinColor.fujin;
  static const Color texteOr = FujinColor.kinFonce;
  static const Color textePrincipal = FujinColor.sumi;
  static const Color texteSecondaire = FujinColor.hai;
  static const Color texteSurSombre = FujinColor.kinu;
  static const Color texteTertiaire = FujinColor.haiClair;
}

abstract final class FujinSpace {
  static const double s1 = 4;
  static const double s2 = 8;
  static const double s3 = 12;
  static const double s4 = 16;
  static const double s5 = 20;
  static const double s6 = 24;
  static const double s8 = 32;
}

abstract final class FujinRadius {
  static const double barre = 2;
  static const double bouton = 28;
  static const double carte = 20;
  static const double champ = 16;
  static const double feuille = 28;
  static const double pastille = 999;
}

abstract final class FujinStroke {
  static const double anneauJour = 1.5;
  static const double anneauMacro = 2;
  static const double carte = 1;
  static const double icone = 1.75;
}

abstract final class FujinSize {
  static const double anneauJour = 38;
  static const double anneauMacro = 52;
  static const double barreKcal = 6;
  static const double barreMacro = 4;
  static const double boutonHauteur = 56;
  static const double boutonMoyen = 48;
  static const double icone = 24;
  static const double margeEcran = 16;
  static const double pastille = 26;
  static const double pastilleJour = 26;
  static const double pastillePetite = 20;
  static const double retraitTexte = 24;
  static const double zoneTactile = 48;
}

abstract final class FujinFont {
  static const hina = 'Hina Mincho';
  static const inter = 'Inter';
}

abstract final class FujinText {
  static const hina22 = TextStyle(
    fontFamily: FujinFont.hina,
    fontSize: 22,
    fontWeight: FontWeight.w400,
    height: 1.2,
    letterSpacing: 0,
  );
  static const hina24 = TextStyle(
    fontFamily: FujinFont.hina,
    fontSize: 24,
    fontWeight: FontWeight.w400,
    height: 1.25,
    letterSpacing: 0,
  );
  static const hina26 = TextStyle(
    fontFamily: FujinFont.hina,
    fontSize: 26,
    fontWeight: FontWeight.w400,
    height: 1.231,
    letterSpacing: 0,
  );
  static const hina28 = TextStyle(
    fontFamily: FujinFont.hina,
    fontSize: 28,
    fontWeight: FontWeight.w400,
    height: 1.2,
    letterSpacing: 0,
  );
  static const hina30 = TextStyle(
    fontFamily: FujinFont.hina,
    fontSize: 30,
    fontWeight: FontWeight.w400,
    height: 1.2,
    letterSpacing: 0,
  );
  static const hina44 = TextStyle(
    fontFamily: FujinFont.hina,
    fontSize: 44,
    fontWeight: FontWeight.w400,
    height: 1.2,
    letterSpacing: 0,
  );
  static const inter10Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 10,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter11Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 11,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter11Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 11,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter11Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 11,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter12Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 12,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter12Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 12,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter12RegularL16 = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 12,
    fontWeight: FontWeight.w400,
    height: 1.333,
    letterSpacing: 0,
  );
  static const inter12Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 12,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter13Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 13,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter13Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 13,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter13RegularL19 = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 13,
    fontWeight: FontWeight.w400,
    height: 1.462,
    letterSpacing: 0,
  );
  static const inter13Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 13,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter14Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 14,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter14Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 14,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter14RegularL20 = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 14,
    fontWeight: FontWeight.w400,
    height: 1.429,
    letterSpacing: 0,
  );
  static const inter14Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 14,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter15Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 15,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter15Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 15,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter15RegularL22 = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 15,
    fontWeight: FontWeight.w400,
    height: 1.467,
    letterSpacing: 0,
  );
  static const inter15Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 15,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter16Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 16,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter16Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 16,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter17Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 17,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter18Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 18,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter20Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 20,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter22Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 22,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter22Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 22,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter28Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 28,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
}
