// GENERATED by tool/generate_tokens.dart. Do not edit.

import 'package:flutter/painting.dart';

abstract final class FujinColor {
  static const ekklo = Color(0xFF7A4BC9);
  static const ekkloDark = Color(0xFF5B3A99);
  static const ekkloLight = Color(0xFFECE5F7);
  static const fujin = Color(0xFF2F5E34);
  static const hai = Color(0xFF6F6857);
  static const haiLight = Color(0xFF8A826C);
  static const kin = Color(0xFFD4A548);
  static const kinDark = Color(0xFF8C6418);
  static const kinLight = Color(0xFFF3E6C4);
  static const kinari = Color(0xFFE3DAC0);
  static const kinu = Color(0xFFFFFCF4);
  static const matcha = Color(0xFFDCE8D5);
  static const mfp = Color(0xFF1E6BD6);
  static const mfpLight = Color(0xFFDCE6F7);
  static const mfpMedium = Color(0xFFBBD0EB);
  static const shu = Color(0xFFB23A26);
  static const shuLight = Color(0xFFF4DDD6);
  static const sora = Color(0xFF3F6A82);
  static const soraLight = Color(0xFFDDE7EC);
  static const sumi = Color(0xFF1B1A17);
  static const usuzumi = Color(0xFFBDB49C);
  static const washi = Color(0xFFF7F1E0);
}

abstract final class FujinColorRole {
  static const Color backgroundAlert = FujinColor.shuLight;
  static const Color backgroundCard = FujinColor.kinu;
  static const Color backgroundDark = FujinColor.sumi;
  static const Color backgroundInfo = FujinColor.soraLight;
  static const Color backgroundPage = FujinColor.washi;
  static const Color backgroundSuccess = FujinColor.matcha;
  static const Color borderCard = FujinColor.kinari;
  static const Color borderDivider = FujinColor.kin;
  static const Color borderHairline = FujinColor.kinari;
  static const Color buttonAlertBackground = FujinColor.shu;
  static const Color buttonAlertText = FujinColor.kinu;
  static const Color buttonDisabledBackground = FujinColor.kinari;
  static const Color buttonDisabledText = FujinColor.haiLight;
  static const Color buttonPrimaryBackground = FujinColor.sumi;
  static const Color buttonPrimaryText = FujinColor.kinu;
  static const Color goalExceeded = FujinColor.shu;
  static const Color goalExceededBackground = FujinColor.shuLight;
  static const Color goalInProgress = FujinColor.mfp;
  static const Color goalMinimumLeft = FujinColor.mfpMedium;
  static const Color goalMissed = FujinColor.mfp;
  static const Color goalMissedBackground = FujinColor.mfpLight;
  static const Color goalReached = FujinColor.fujin;
  static const Color goalReachedBackground = FujinColor.matcha;
  static const Color goalSelectedDay = FujinColor.sumi;
  static const Color goalTrack = FujinColor.kinari;
  static const Color sourceEkklo = FujinColor.ekklo;
  static const Color sourceEkkloBackground = FujinColor.ekkloLight;
  static const Color sourceEkkloText = FujinColor.ekkloDark;
  static const Color sourceMfp = FujinColor.mfp;
  static const Color textAlert = FujinColor.shu;
  static const Color textDisabled = FujinColor.usuzumi;
  static const Color textGold = FujinColor.kinDark;
  static const Color textInfo = FujinColor.sora;
  static const Color textLink = FujinColor.fujin;
  static const Color textOnDark = FujinColor.kinu;
  static const Color textPrimary = FujinColor.sumi;
  static const Color textSecondary = FujinColor.hai;
  static const Color textTertiary = FujinColor.haiLight;
  static const backgroundGlass = Color(0x66FFFCF4);
  static const backgroundScrim = Color(0x801B1A17);
  static const backgroundScrollFade = Color(0x8CF7F1E0);
  static const backgroundTabActive = Color(0xCCDCE8D5);
  static const shadowFloating = Color(0x1F1B1A17);
  static const shadowLogo = Color(0x1A1B1A17);
}

abstract final class FujinSpace {
  static const double s1 = 4;
  static const double s2 = 8;
  static const double s3 = 12;
  static const double s4 = 16;
  static const double s5 = 20;
  static const double s6 = 24;
  static const double s8 = 32;
}

abstract final class FujinRadius {
  static const double bar = 2;
  static const double button = 28;
  static const double card = 20;
  static const double field = 16;
  static const double hint = 12;
  static const double logo = 36;
  static const double menu = 12;
  static const double pill = 999;
  static const double sheet = 28;
  static const double stateCard = 28;
  static const double tile = 10;
  static const double toast = 16;
}

abstract final class FujinStroke {
  static const double card = 1;
  static const double dayRing = 1.5;
  static const double fieldError = 1.5;
  static const double fieldFocus = 1.5;
  static const double goldRule = 2;
  static const double icon = 1.75;
  static const double macroRing = 2;
  static const double radio = 1.5;
  static const double streak = 2;
}

abstract final class FujinSize {
  static const double bandFade = 28;
  static const double bandNudge = 44;
  static const double breezeGap = 3;
  static const double breezeIndicator = 24;
  static const double breezeInsetBottom = 1;
  static const double breezeInsetTop = 3;
  static const double buttonHeight = 56;
  static const double buttonMedium = 48;
  static const double controlHeight = 40;
  static const double dayPill = 26;
  static const double dayRing = 38;
  static const double dragHandleHeight = 4;
  static const double dragHandleWidth = 36;
  static const double floatingShadowBlur = 20;
  static const double floatingShadowOffset = 6;
  static const double glassBlur = 12;
  static const double glyphCard = 56;
  static const double glyphHero = 72;
  static const double goalFieldGap = 10;
  static const double goldRuleWidth = 48;
  static const double hintIcon = 18;
  static const double hintPaddingEnd = 14;
  static const double hintPaddingVertical = 10;
  static const double hintPointerHeight = 8;
  static const double hintPointerInset = 26;
  static const double hintPointerWidth = 14;
  static const double icon = 24;
  static const double kcalBar = 6;
  static const double logo = 160;
  static const double logoShadowBlur = 24;
  static const double logoShadowOffset = 8;
  static const double macroBar = 4;
  static const double macroRing = 52;
  static const double macroRingDash = 3;
  static const double macroRingDashGap = 2;
  static const double mealArrow = 18;
  static const double menuChevron = 14;
  static const double menuWidth = 140;
  static const double motifBand = 252;
  static const double motifBandSplash = 180;
  static const double pictogram = 52;
  static const double pictogramIcon = 36;
  static const double pill = 26;
  static const double pillSmall = 20;
  static const double radio = 20;
  static const double radioDot = 10;
  static const double rowChevron = 20;
  static const double scanIcon = 26;
  static const double screenMargin = 16;
  static const double scrollFade = 110;
  static const double searchField = 44;
  static const double searchIcon = 20;
  static const double skeletonLine = 10;
  static const double skeletonMacro = 8;
  static const double skeletonMacroWidth = 50;
  static const double skeletonMealDetail = 180;
  static const double skeletonMealTitle = 120;
  static const double skeletonMedium = 140;
  static const double skeletonPill = 22;
  static const double skeletonPillWidth = 80;
  static const double skeletonTitle = 12;
  static const double skeletonWide = 200;
  static const double sourceDot = 8;
  static const double splashRuleGap = 58;
  static const double splashTitleGap = 36;
  static const double stepIcon = 14;
  static const double stepMarker = 28;
  static const double streakLong = 18;
  static const double streakMedium = 14;
  static const double streakOffset = 6;
  static const double streakOffsetSmall = 2;
  static const double streakShort = 10;
  static const double streakTransitLong = 40;
  static const double streakTransitShort = 24;
  static const double tab = 56;
  static const double tabBar = 68;
  static const double tabGap = 2;
  static const double tabPlateInset = 6;
  static const double textGap = 3;
  static const double textInset = 24;
  static const double tile = 32;
  static const double tileIcon = 16;
  static const double touchTarget = 48;
  static const double transitLane = 38;
  static const double volute = 22;
  static const double weekBand = 64;
  static const double weightField = 120;
}

abstract final class FujinFont {
  static const hina = 'Hina Mincho';
  static const inter = 'Inter';
}

abstract final class FujinText {
  static const hina22 = TextStyle(
    fontFamily: FujinFont.hina,
    fontSize: 22,
    fontWeight: FontWeight.w400,
    height: 1.2,
    letterSpacing: 0,
  );
  static const hina24 = TextStyle(
    fontFamily: FujinFont.hina,
    fontSize: 24,
    fontWeight: FontWeight.w400,
    height: 1.25,
    letterSpacing: 0,
  );
  static const hina26 = TextStyle(
    fontFamily: FujinFont.hina,
    fontSize: 26,
    fontWeight: FontWeight.w400,
    height: 1.231,
    letterSpacing: 0,
  );
  static const hina28 = TextStyle(
    fontFamily: FujinFont.hina,
    fontSize: 28,
    fontWeight: FontWeight.w400,
    height: 1.2,
    letterSpacing: 0,
  );
  static const hina30 = TextStyle(
    fontFamily: FujinFont.hina,
    fontSize: 30,
    fontWeight: FontWeight.w400,
    height: 1.2,
    letterSpacing: 0,
  );
  static const hina44 = TextStyle(
    fontFamily: FujinFont.hina,
    fontSize: 44,
    fontWeight: FontWeight.w400,
    height: 1.2,
    letterSpacing: 0,
  );
  static const inter10Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 10,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter11Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 11,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter11Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 11,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter11Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 11,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter12Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 12,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter12Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 12,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter12RegularL16 = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 12,
    fontWeight: FontWeight.w400,
    height: 1.333,
    letterSpacing: 0,
  );
  static const inter12Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 12,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter13Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 13,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter13Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 13,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter13RegularL19 = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 13,
    fontWeight: FontWeight.w400,
    height: 1.462,
    letterSpacing: 0,
  );
  static const inter13Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 13,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter14Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 14,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter14Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 14,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter14RegularL20 = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 14,
    fontWeight: FontWeight.w400,
    height: 1.429,
    letterSpacing: 0,
  );
  static const inter14Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 14,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter15Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 15,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter15Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 15,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter15RegularL22 = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 15,
    fontWeight: FontWeight.w400,
    height: 1.467,
    letterSpacing: 0,
  );
  static const inter15Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 15,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter16Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 16,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter16Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 16,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter17Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 17,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter18Medium = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 18,
    fontWeight: FontWeight.w500,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter20Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 20,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter22Regular = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 22,
    fontWeight: FontWeight.w400,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter22Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 22,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
  static const inter28Semibold = TextStyle(
    fontFamily: FujinFont.inter,
    fontSize: 28,
    fontWeight: FontWeight.w600,
    height: 1.21,
    letterSpacing: 0,
  );
}
