import 'dart:convert';
import 'dart:io';

const _input = 'design/tokens/fujin.tokens.json';
const _output = 'lib/app/theme/fujin_tokens.g.dart';
const _header = '// GENERATED by tool/generate_tokens.dart. Do not edit.';
const _valueKey = r'$value';
const _typeKey = r'$type';
const _meta = r'$';
const _colorClass = 'FujinColor';
const _fontClass = 'FujinFont';

typedef _Token = ({String type, Object? value});

final class _Group {
  const _Group({
    required this.path,
    required this.className,
    required this.render,
  });

  final String path;
  final String className;
  final String Function(String name, _Token token) render;
}

Future<void> main() async {
  final source = await File(_input).readAsString();
  final tokens = <String, _Token>{};
  _collect(jsonDecode(source), const [], tokens);

  String resolvePath(String alias) {
    final path = alias.substring(1, alias.length - 1).replaceAll('.', '/');
    return switch (tokens[path]) {
      _Token(:final String value) when _isAlias(value) => resolvePath(value),
      _Token() => path,
      null => throw FormatException('Unknown alias $alias'),
    };
  }

  Object? resolveValue(Object? value) => switch (value) {
    final String alias when _isAlias(alias) => resolveValue(
      tokens[resolvePath(alias)]?.value,
    ),
    _ => value,
  };

  String member(String path, String group) =>
      _identifier(path.substring(group.length + 1));

  String dimension(String name, _Token token) =>
      'static const double $name = ${_number(_dimension(token.value))};';

  final groups = [
    _Group(
      path: 'couleur',
      className: _colorClass,
      render: (name, token) =>
          'static const $name = Color(${_color(token.value)});',
    ),
    _Group(
      path: 'role',
      className: 'FujinRole',
      render: (name, token) => switch (token.value) {
        final String alias when _isAlias(alias) =>
          'static const Color $name = '
              '$_colorClass.${member(resolvePath(alias), 'couleur')};',
        _ => 'static const $name = Color(${_color(token.value)});',
      },
    ),
    _Group(path: 'espace', className: 'FujinSpace', render: dimension),
    _Group(path: 'rayon', className: 'FujinRadius', render: dimension),
    _Group(path: 'trait', className: 'FujinStroke', render: dimension),
    _Group(path: 'taille', className: 'FujinSize', render: dimension),
    _Group(
      path: 'police/famille',
      className: _fontClass,
      render: (name, token) => switch (token.value) {
        [final String family, ...] => "static const $name = '$family';",
        final String family => "static const $name = '$family';",
        _ => throw FormatException('Invalid font family for $name'),
      },
    ),
    _Group(
      path: 'texte',
      className: 'FujinText',
      render: (name, token) => switch (token.value) {
        final Map<String, Object?> style => _textStyle(
          name: name,
          style: style,
          family: member(
            resolvePath('${style['fontFamily']}'),
            'police/famille',
          ),
          weight: resolveValue(style['fontWeight']),
        ),
        _ => throw FormatException('Invalid typography for $name'),
      },
    ),
  ];

  final buffer = StringBuffer()
    ..writeln(_header)
    ..writeln()
    ..writeln("import 'package:flutter/painting.dart';");

  for (final group in groups) {
    final prefix = '${group.path}/';
    final members = [
      for (final MapEntry(key: path, value: token) in tokens.entries)
        if (path.startsWith(prefix))
          group.render(member(path, group.path), token),
    ]..sort();
    buffer
      ..writeln()
      ..writeln('abstract final class ${group.className} {')
      ..writeAll(members.map((line) => '  $line\n'))
      ..writeln('}');
  }

  await File(_output).writeAsString(buffer.toString());
  final format = await Process.run('dart', ['format', _output]);
  stdout.write(format.stdout);
  stderr.write(format.stderr);
  exitCode = format.exitCode;
}

void _collect(Object? node, List<String> path, Map<String, _Token> tokens) {
  switch (node) {
    case {_valueKey: final Object? value}:
      tokens[path.join('/')] = (type: '${node[_typeKey]}', value: value);
    case final Map<String, Object?> group:
      for (final MapEntry(:key, :value) in group.entries) {
        switch (key.startsWith(_meta)) {
          case true:
            break;
          case false:
            _collect(value, [...path, key], tokens);
        }
      }
  }
}

bool _isAlias(String value) => value.startsWith('{') && value.endsWith('}');

String _identifier(String path) {
  final words = path.split(RegExp('[-/_ ]')).where((w) => w.isNotEmpty);
  final camel = words.indexed
      .map(
        (entry) => switch (entry) {
          (0, final word) => word.toLowerCase(),
          (_, final word) =>
            word[0].toUpperCase() + word.substring(1).toLowerCase(),
        },
      )
      .join();
  return switch (RegExp('^[0-9]').hasMatch(camel)) {
    true => 's$camel',
    false => camel,
  };
}

String _color(Object? value) => switch (value) {
  {'hex': final String hex, 'alpha': final num alpha} => _argb(hex, alpha),
  {'hex': final String hex} => _argb(hex, 1),
  _ => throw FormatException('Invalid color $value'),
};

String _argb(String hex, num alpha) {
  final alphaHex = (alpha * 255).round().toRadixString(16).padLeft(2, '0');
  return '0x${'$alphaHex${hex.substring(1)}'.toUpperCase()}';
}

num _dimension(Object? value) => switch (value) {
  {'value': final num number, 'unit': 'px'} => number,
  final num number => number,
  _ => throw FormatException('Invalid dimension $value'),
};

String _number(num value) {
  final rounded = double.parse(value.toStringAsFixed(3));
  return switch (rounded == rounded.roundToDouble()) {
    true => '${rounded.round()}',
    false => '$rounded',
  };
}

String _textStyle({
  required String name,
  required Map<String, Object?> style,
  required String family,
  required Object? weight,
}) {
  final fontSize = _dimension(style['fontSize']);
  final fontWeight = switch (weight) {
    final int value when value % 100 == 0 => 'FontWeight.w$value',
    final num value => 'FontWeight(${_number(value)})',
    _ => throw FormatException('Invalid font weight for $name'),
  };
  final height = switch (style['lineHeight']) {
    null => null,
    final num ratio => ratio,
    final Object dimension => _dimension(dimension) / fontSize,
  };
  final letterSpacing = switch (style['letterSpacing']) {
    null => null,
    final Object spacing => _dimension(spacing),
  };
  final arguments = [
    'fontFamily: $_fontClass.$family',
    'fontSize: ${_number(fontSize)}',
    'fontWeight: $fontWeight',
    if (height != null) 'height: ${_number(height)}',
    if (letterSpacing != null) 'letterSpacing: ${_number(letterSpacing)}',
  ];
  return 'static const $name = TextStyle(${arguments.join(', ')},);';
}
